"""
Django settings for SSAPI project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
_key_env = BASE_DIR / "key.env"
_dev_env = BASE_DIR / "dev.env"
if _key_env.exists():
    load_dotenv(_key_env)
elif (BASE_DIR / ".env" / "key.env").exists():
    load_dotenv(BASE_DIR / ".env" / "key.env")
if _dev_env.exists():
    load_dotenv(_dev_env, override=True)
else:
    load_dotenv()

from .db import get_databases


def _csv_env(*names: str, default: str = "") -> list[str]:
    for name in names:
        raw = os.getenv(name)
        if raw is not None and raw.strip():
            return [item.strip() for item in raw.split(",") if item.strip()]
    return [item.strip() for item in default.split(",") if item.strip()]

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# Debe coincidir con Portal-Paldaca/key.env para compartir sesion SSO.
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY", os.getenv("SECRET_KEY", "")).strip()
if not SECRET_KEY:
    raise ValueError(
        "DJANGO_SECRET_KEY no definida. En Coolify configúrala como variable "
        "de entorno; en local copia key.env desde Portal-Paldaca."
    )

# SECURITY WARNING: don't run with debug turned on in production!
# Sin DJANGO_DEBUG: true solo si hay dev.env (local); en servidor queda false.
DEBUG = os.getenv(
    "DJANGO_DEBUG",
    "true" if _dev_env.exists() else "false",
).lower() == "true"

_default_hosts = [
    "127.0.0.1",
    "localhost",
    "activos.cpaldaca.com",
    "www.activos.cpaldaca.com",
    ".cereipo.com",
]
ALLOWED_HOSTS = _csv_env("DJANGO_ALLOWED_HOSTS", "ALLOWED_HOSTS") or _default_hosts
_coolify_fqdn = os.getenv("COOLIFY_FQDN", "").strip()
if _coolify_fqdn and _coolify_fqdn not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append(_coolify_fqdn)
if "*" not in ALLOWED_HOSTS and ".cereipo.com" not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append(".cereipo.com")


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'activos',
    'core',
    'reportes',
    'usuarios',  # solo historial de migraciones; identidad en core.UsuarioPaldaca
    'mantenimientos',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'core.performance.DevelopmentPerformanceMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    # Despues de Authentication (necesita request.user) y ANTES de
    # PaldacaSessionMiddleware (que puede cortocircuitar y necesita saber si la
    # peticion viene embebida). Su fase de respuesta corre despues de todos los
    # de abajo, asi que tiene la ultima palabra sobre las cabeceras de framing.
    'core.embed.PaldacaEmbedMiddleware',
    'core.middleware.PaldacaSessionMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    # XFrameOptionsMiddleware retirado: emitia X-Frame-Options: DENY (default de
    # Django al no definir X_FRAME_OPTIONS), lo que impide embeber el modulo en
    # el shell del Portal. El control de framing lo hace ahora PaldacaEmbedMiddleware
    # con CSP frame-ancestors, que si admite lista de origenes.
    'core.middleware.ErrorHandlingMiddleware',
    'core.middleware.SecurityHeadersMiddleware',
]

ROOT_URLCONF = 'SSAPI.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.paldaca_urls',
            ],
            'libraries': {
                'cache_bust': 'core.templatetags.cache_bust',
            },
        },
    },
]

WSGI_APPLICATION = 'SSAPI.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
# DATABASE_URL (MySQL compartida en Coolify) tiene prioridad; si no existe, MySQL local/Namecheap.
DATABASES = get_databases()

AUTH_USER_MODEL = "core.UsuarioPaldaca"

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'es-es'

TIME_ZONE = 'America/Caracas'

USE_I18N = True

USE_TZ = True

PALDACA_SSO_LOGIN_URL = os.getenv("PALDACA_SSO_LOGIN_URL", "http://localhost:5173/login/")
PALDACA_SSO_LOGOUT_URL = os.getenv(
    "PALDACA_SSO_LOGOUT_URL",
    "http://localhost:8000/api/auth/sso/logout/",
)
PALDACA_STRICT_SESSION_CONSISTENCY = os.getenv(
    "PALDACA_STRICT_SESSION_CONSISTENCY",
    "true",
)

# --- Portal unificado: este modulo embebido en el shell ---------------------
# Codigo de modulo de la Suite. Lo lee core/embed.py para que ese fichero sea
# copiable sin cambios a Calidad, Codigos y HojadeTiempo.
PALDACA_MODULO_CODIGO = "activos"

# Origen del shell. Debe coincidir EXACTAMENTE con el origen desde el que se
# sirve el SPA: es el targetOrigin de postMessage y el que valida el Portal.
PALDACA_PORTAL_URL = (
    (os.getenv("PALDACA_PORTAL_URL") or "").strip().rstrip("/")
    or ("http://localhost:5173" if _dev_env.exists() else "https://cpaldaca.com")
)

# Ruta del modulo dentro del shell: cpaldaca.com/activos/<ruta del satelite>.
PALDACA_SHELL_PATH = os.getenv("PALDACA_SHELL_PATH", "/activos")

# Quien puede enmarcar este satelite. Sustituye a X-Frame-Options, que no
# admite lista de origenes (SAMEORIGIN no vale: son origenes distintos).
_frame_ancestors = ["'self'", PALDACA_PORTAL_URL]
if _dev_env.exists():
    _frame_ancestors += ["http://localhost:5173", "http://127.0.0.1:5173"]
else:
    _frame_ancestors += ["https://cpaldaca.com", "https://www.cpaldaca.com"]
PALDACA_FRAME_ANCESTORS = os.getenv(
    "PALDACA_FRAME_ANCESTORS",
    " ".join(dict.fromkeys(a for a in _frame_ancestors if a)),
)

# Redirige activos.cpaldaca.com/<ruta> -> cpaldaca.com/activos/<ruta> cuando la
# navegacion es top-level. Refuerza la percepcion de aplicacion unica y hace que
# los marcadores antiguos sigan funcionando. Valvula de escape para depurar el
# satelite suelto: ?paldaca_standalone=1
PALDACA_EMBED_REDIRECT_TO_SHELL = os.getenv(
    "PALDACA_EMBED_REDIRECT_TO_SHELL",
    "false",
).lower() == "true"

# Rutas que NUNCA se redirigen al shell del Portal. Se replica la lista por
# defecto de core.embed y se anade /q/ (ficha publica de una etiqueta QR): esa
# pagina se abre escaneando un adhesivo con la camara del telefono y debe
# funcionar suelta, sin sesion. Si se redirigiera, quien ya tuviera sesion
# acabaria viendo la ficha dentro del iframe del Portal.
PALDACA_EMBED_EXCLUDED_PREFIXES = (
    "/admin/",
    "/static/",
    "/media/",
    "/logout/",
    "/healthz/",
    "/q/",
)

# Origen absoluto que se imprime dentro del QR. Debe ser el subdominio del
# satelite, NUNCA la ruta dentro del shell: la etiqueta se pega una vez y tiene
# que resolver aunque el Portal no este por medio.
PALDACA_PUBLIC_BASE_URL = (
    (os.getenv("PALDACA_PUBLIC_BASE_URL") or "").strip().rstrip("/")
    or ("http://localhost:8001" if _dev_env.exists() else "https://activos.cpaldaca.com")
)

SESSION_COOKIE_NAME = os.getenv("SESSION_COOKIE_NAME", "paldaca_sessionid")
_raw_cookie_domain = (os.getenv("SESSION_COOKIE_DOMAIN") or "").strip()
SESSION_COOKIE_DOMAIN = (
    f".{_raw_cookie_domain.lstrip('.')}" if _raw_cookie_domain else None
)
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = "Lax"
SESSION_COOKIE_SECURE = (
    os.getenv("SESSION_COOKIE_SECURE", "true" if SESSION_COOKIE_DOMAIN else "false").lower()
    == "true"
)
CSRF_COOKIE_DOMAIN = SESSION_COOKIE_DOMAIN
CSRF_COOKIE_SECURE = SESSION_COOKIE_SECURE
USE_X_FORWARDED_HOST = True
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

if DEBUG and not _raw_cookie_domain:
    SESSION_COOKIE_DOMAIN = None
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_DOMAIN = None
    CSRF_COOKIE_SECURE = False
    CSRF_TRUSTED_ORIGINS = [
        "http://localhost:5173",
        "http://localhost:8000",
        "http://localhost:8001",
        "http://localhost:8002",
        "http://localhost:8083",
        "http://127.0.0.1:8083",
    ]
elif SESSION_COOKIE_DOMAIN:
    CSRF_TRUSTED_ORIGINS = [
        "https://cpaldaca.com",
        "https://www.cpaldaca.com",
        "https://api.cpaldaca.com",
        "https://activos.cpaldaca.com",
        "https://www.activos.cpaldaca.com",
    ]
else:
    CSRF_TRUSTED_ORIGINS = [
        "https://cpaldaca.com",
        "https://www.cpaldaca.com",
        "https://api.cpaldaca.com",
        "https://activos.cpaldaca.com",
        "https://www.activos.cpaldaca.com",
    ]

_csrf_extra = _csv_env("CSRF_TRUSTED_ORIGINS")
for origin in _csrf_extra:
    if origin not in CSRF_TRUSTED_ORIGINS:
        CSRF_TRUSTED_ORIGINS.append(origin)
_coolify_url = (os.getenv("COOLIFY_URL") or "").strip().rstrip("/")
if _coolify_url and _coolify_url not in CSRF_TRUSTED_ORIGINS:
    CSRF_TRUSTED_ORIGINS.append(_coolify_url)

_CEREIPO_CSRF_ORIGINS = (
    "https://cereipo.com",
    "https://www.cereipo.com",
    "https://activos.cereipo.com",
    "https://www.activos.cereipo.com",
)
for _origin in _CEREIPO_CSRF_ORIGINS:
    if _origin not in CSRF_TRUSTED_ORIGINS:
        CSRF_TRUSTED_ORIGINS.append(_origin)

LOGIN_URL = PALDACA_SSO_LOGIN_URL
LOGIN_REDIRECT_URL = 'core:home'
LOGOUT_REDIRECT_URL = PALDACA_SSO_LOGOUT_URL

# Configuración de manejo de errores
handler404 = 'core.views.custom_404_view'
handler500 = 'core.views.custom_500_view'
handler403 = 'core.views.custom_403_view'
handler400 = 'core.views.custom_400_view'

# Logging: sin esto, 'paldaca.performance' (core/performance.py) hereda el
# nivel WARNING del root logger de Django y logger.info(...) nunca se emite,
# pese a que Server-Timing sí llega en la respuesta. Mismo patrón que
# Calidad/Codigos/HDT.
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'simple': {
            'format': '{levelname} {asctime} {message}',
            'style': '{',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
    },
    'handlers': {
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'paldaca.performance': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedStaticFilesStorage",
    },
}


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
