# Generated by Django 5.2.7 on 2026-08-27 19:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0005_rename_activos_his_activo__b4a8a8_idx_activos_his_activo__580f3c_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EtiquetaQR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(editable=False, help_text='Identificador opaco que viaja en el QR. Inmutable.', max_length=16, unique=True)),
                ('codigo_reservado', models.CharField(help_text='Código de inventario apartado al imprimir; se traspasa al activo.', max_length=50, unique=True)),
                ('estado', models.CharField(choices=[('PE', 'Pendiente'), ('VI', 'Vinculada'), ('AN', 'Anulada')], default='PE', max_length=2)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_vinculacion', models.DateTimeField(blank=True, null=True)),
                ('activo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='etiquetas', to='activos.activo')),
                ('creada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='etiquetas_generadas', to=settings.AUTH_USER_MODEL)),
                ('subcategoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='etiquetas', to='activos.subcategoria')),
            ],
            options={
                'verbose_name': 'Etiqueta QR',
                'verbose_name_plural': 'Etiquetas QR',
                'db_table': 'activos_etiqueta_qr',
                'ordering': ['-fecha_creacion', 'codigo_reservado'],
                'indexes': [models.Index(fields=['token'], name='activos_eti_token_743e53_idx'), models.Index(fields=['estado'], name='activos_eti_estado_cf74ab_idx'), models.Index(fields=['subcategoria'], name='activos_eti_subcate_53f4f9_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('estado', 'VI')), fields=('activo',), name='activos_etiqueta_qr_una_vigente_por_activo')],
            },
        ),
    ]
