# Generated by Django 5.2.7 on 2026-08-28 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0006_etiquetaqr'),
    ]

    operations = [
        migrations.AddField(
            model_name='activo',
            name='planilla_generada_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activo',
            name='planilla_pdf',
            field=models.FileField(blank=True, null=True, upload_to='planillas/'),
        ),
        migrations.AddField(
            model_name='historialmovimiento',
            name='archivo_planilla',
            field=models.FileField(blank=True, null=True, upload_to='planillas/'),
        ),
        migrations.AlterField(
            model_name='historialmovimiento',
            name='tipo_movimiento',
            field=models.CharField(choices=[('CR', 'Creación'), ('AC', 'Actualización'), ('RE', 'Reasignación'), ('RU', 'Reubicación'), ('CE', 'Cambio de Estado'), ('EL', 'Eliminación'), ('PA', 'Planilla')], max_length=2),
        ),
    ]
