# Generated by Django 5.2.7 on 2026-09-16 14:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0009_historial_archivo_planilla'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AvisoUsuarioInactivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enviado_en', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='aviso_inactivo_activos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Aviso de usuario inactivo',
                'verbose_name_plural': 'Avisos de usuario inactivo',
                'db_table': 'activos_aviso_usuario_inactivo',
            },
        ),
    ]
