# Generated by Django 5.2.7 on 2026-09-16 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0010_aviso_usuario_inactivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvisoPorUmbral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regla', models.CharField(choices=[('etiqueta_sin_vincular', 'Etiqueta sin vincular'), ('asignacion_sin_planilla', 'Asignación sin planilla')], max_length=32)),
                ('objeto_id', models.PositiveIntegerField(help_text='pk de EtiquetaQR o HistorialMovimiento, según la regla.')),
                ('enviado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Aviso por umbral',
                'verbose_name_plural': 'Avisos por umbral',
                'db_table': 'activos_aviso_por_umbral',
                'constraints': [models.UniqueConstraint(fields=('regla', 'objeto_id'), name='activos_aviso_por_umbral_unico')],
            },
        ),
    ]
